import React, { useState, useEffect } from 'react';
import {
  View, Text, TextInput, TouchableOpacity, ScrollView,
  StyleSheet, SafeAreaView, Share, Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { getJournalEntries } from '../services/storage';
import { colors, fonts, spacing, radius } from '../theme';

const STEPS = [
  {
    id: 'frequency',
    title: 'How often do you get migraines?',
    type: 'options',
    options: ['1–3 days per month', '4–7 days per month', '8–14 days per month', '15+ days per month'],
  },
  {
    id: 'impact',
    title: 'How do migraines affect your daily life?',
    type: 'multiselect',
    options: [
      'Miss work or school',
      'Cancel social plans',
      'Can\'t care for family',
      'Affects my relationships',
      'Limits physical activity',
      'Causes anxiety about future attacks',
    ],
  },
  {
    id: 'treatments',
    title: 'What treatments have you tried?',
    subtitle: 'Include anything: over-the-counter, prescription, lifestyle changes.',
    type: 'text',
  },
  {
    id: 'goal',
    title: 'What do you most want from treatment?',
    type: 'options',
    options: [
      'Fewer migraine days overall',
      'Less severe migraines when they happen',
      'Being able to function through a migraine',
      'Reducing how much rescue medication I use',
    ],
  },
];

function frequencyFromJournalDays(days) {
  if (days >= 15) return '15+ days per month';
  if (days >= 8) return '8–14 days per month';
  if (days >= 4) return '4–7 days per month';
  return '1–3 days per month';
}

function generateSummary(answers, journalStats) {
  const lines = ['📋 MY MIGRAINE SUMMARY: for my healthcare provider\n'];

  if (journalStats && journalStats.daysLogged > 0) {
    lines.push('From my journal (last 30 days):');
    lines.push(`  Migraine days: ${journalStats.migraineDays} out of ${journalStats.daysLogged} days logged`);
    if (journalStats.avgSeverity) {
      lines.push(`  Average severity: ${journalStats.avgSeverity} / 10`);
    }
    if (journalStats.topTriggers.length > 0) {
      lines.push(`  Most common triggers: ${journalStats.topTriggers.join(', ')}`);
    }
    lines.push('');
  }

  lines.push(`Self-reported frequency: ${answers.frequency || 'Not specified'}`);
  if (answers.impact && answers.impact.length > 0) {
    lines.push(`Daily impact: ${answers.impact.join(', ')}`);
  }
  if (answers.treatments) {
    lines.push(`Treatments I have tried: ${answers.treatments}`);
  }
  if (answers.goal) {
    lines.push(`My treatment goal: ${answers.goal}`);
  }
  lines.push('\nGenerated by Migraine Companion. For general informational purposes only. This is not a medical document.');
  return lines.join('\n');
}

export default function HCPPrepScreen({ navigation }) {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [done, setDone] = useState(false);
  const [journalStats, setJournalStats] = useState(null);

  useEffect(() => {
    getJournalEntries().then(entries => {
      const cutoff = new Date();
      cutoff.setDate(cutoff.getDate() - 30);
      const recent = entries.filter(e => new Date(e.date) >= cutoff);
      const migraine = recent.filter(e => e.hadMigraine);

      const avgSeverity = migraine.length > 0
        ? (migraine.reduce((s, e) => s + (e.severity || 0), 0) / migraine.length).toFixed(1)
        : null;

      const trigCounts = {};
      migraine.flatMap(e => e.triggers || []).forEach(t => {
        trigCounts[t] = (trigCounts[t] || 0) + 1;
      });
      const topTriggers = Object.entries(trigCounts)
        .sort((a, b) => b[1] - a[1]).slice(0, 3).map(([k]) => k);

      const stats = {
        daysLogged: new Set(recent.map(e => new Date(e.date).toDateString())).size,
        migraineDays: new Set(migraine.map(e => new Date(e.date).toDateString())).size,
        avgSeverity,
        topTriggers,
      };
      setJournalStats(stats);

      if (migraine.length > 0) {
        setAnswers(prev => ({
          ...prev,
          frequency: prev.frequency || frequencyFromJournalDays(migraine.length),
        }));
      }
    });
  }, []);

  const s = STEPS[step];
  const progress = (step + 1) / STEPS.length;

  function pickOption(value) {
    setAnswers(prev => ({ ...prev, [s.id]: value }));
  }

  function toggleMulti(value) {
    setAnswers(prev => {
      const current = prev[s.id] || [];
      return {
        ...prev,
        [s.id]: current.includes(value)
          ? current.filter(v => v !== value)
          : [...current, value],
      };
    });
  }

  function setText(value) {
    setAnswers(prev => ({ ...prev, [s.id]: value }));
  }

  function canProceed() {
    const val = answers[s.id];
    if (s.type === 'multiselect') return val && val.length > 0;
    if (s.type === 'text') return val && val.trim().length > 0;
    return !!val;
  }

  function handleNext() {
    if (step < STEPS.length - 1) {
      setStep(step + 1);
    } else {
      setDone(true);
    }
  }

  async function handleShare() {
    const summary = generateSummary(answers, journalStats);
    try {
      await Share.share({ message: summary });
    } catch {
      Alert.alert('Could not share', 'Copy the text below and paste it in an email or message to your doctor.');
    }
  }

  if (done) {
    const summary = generateSummary(answers, journalStats);
    return (
      <SafeAreaView style={styles.root}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}>
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
        </View>
        <ScrollView contentContainerStyle={styles.resultBody} showsVerticalScrollIndicator={false}>
          <LinearGradient colors={[colors.lav, '#6B5FAA']} style={styles.resultCard}>
            <Text style={styles.resultIcon}>📋</Text>
            <Text style={styles.resultTitle}>Your appointment summary is ready</Text>
            <Text style={styles.resultDesc}>Share this with your doctor before or at your next appointment.</Text>
          </LinearGradient>

          <View style={styles.summaryBox}>
            <Text style={styles.summaryText}>{summary}</Text>
          </View>

          <TouchableOpacity style={styles.shareBtn} onPress={handleShare} activeOpacity={0.88}>
            <Text style={styles.shareBtnText}>Share with my doctor</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.ghostBtn} onPress={() => { setStep(0); setAnswers({}); setDone(false); }}>
            <Text style={styles.ghostBtnText}>Start over</Text>
          </TouchableOpacity>

          <View style={styles.tipCard}>
            <Text style={styles.tipTitle}>At your appointment</Text>
            <Text style={styles.tipBody}>Ask your doctor: "Based on my migraine frequency and what I've tried, could I be a candidate for preventive therapy?" Then listen for what they recommend and when to expect results.</Text>
          </View>

          <View style={{ height: 110 }} />
        </ScrollView>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.root}>
      <View style={styles.header}>
        <TouchableOpacity onPress={step === 0 ? () => navigation.goBack() : () => setStep(step - 1)} style={styles.back}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <View style={styles.progressBar}>
          <View style={[styles.progressFill, { width: `${progress * 100}%` }]} />
        </View>
        <Text style={styles.stepMeta}>Step {step + 1} of {STEPS.length}</Text>
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false} contentContainerStyle={styles.body}>
        <Text style={styles.eyebrow}>HCP Prep</Text>
        <Text style={styles.question}>{s.title}</Text>
        {s.subtitle && <Text style={styles.subtitle}>{s.subtitle}</Text>}

        {s.id === 'frequency' && journalStats && journalStats.daysLogged > 0 && (
          <View style={styles.journalBadge}>
            <Text style={styles.journalBadgeTitle}>📊 From your journal (last 30 days)</Text>
            <Text style={styles.journalBadgeBody}>
              {journalStats.migraineDays} migraine {journalStats.migraineDays === 1 ? 'day' : 'days'} out of {journalStats.daysLogged} logged
              {journalStats.avgSeverity ? `. Average severity: ${journalStats.avgSeverity}/10.` : '.'}
            </Text>
          </View>
        )}

        {s.type === 'options' && (
          <View style={styles.options}>
            {s.options.map(opt => {
              const selected = answers[s.id] === opt;
              return (
                <TouchableOpacity
                  key={opt}
                  style={[styles.option, selected && styles.optionSel]}
                  onPress={() => pickOption(opt)}
                  activeOpacity={0.85}
                >
                  <View style={[styles.radio, selected && styles.radioSel]}>
                    {selected && <View style={styles.radioDot} />}
                  </View>
                  <Text style={styles.optText}>{opt}</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {s.type === 'multiselect' && (
          <View style={styles.options}>
            {s.options.map(opt => {
              const selected = (answers[s.id] || []).includes(opt);
              return (
                <TouchableOpacity
                  key={opt}
                  style={[styles.option, selected && styles.optionSel]}
                  onPress={() => toggleMulti(opt)}
                  activeOpacity={0.85}
                >
                  <View style={[styles.checkbox, selected && styles.checkboxSel]}>
                    {selected && <Text style={{ color: 'white', fontSize: 17 }}>✓</Text>}
                  </View>
                  <Text style={styles.optText}>{opt}</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {s.type === 'text' && (
          <TextInput
            style={styles.textarea}
            value={answers[s.id] || ''}
            onChangeText={setText}
            placeholder="Type here…"
            placeholderTextColor={colors.slateLight}
            multiline
            numberOfLines={4}
            textAlignVertical="top"
          />
        )}
      </ScrollView>

      <View style={styles.footer}>
        <TouchableOpacity
          style={[styles.btn, !canProceed() && { opacity: 0.35 }]}
          onPress={handleNext}
          disabled={!canProceed()}
          activeOpacity={0.88}
        >
          <Text style={styles.btnText}>
            {step === STEPS.length - 1 ? 'Generate summary' : 'Continue'}
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.white },
  header: { paddingHorizontal: spacing.lg, paddingTop: spacing.md },
  back: { marginBottom: spacing.md },
  backText: { fontFamily: fonts.body, fontSize: 16, color: colors.slateMid },
  progressBar: { height: 4, backgroundColor: colors.creamMid, borderRadius: radius.full, marginBottom: 6 },
  progressFill: { height: '100%', backgroundColor: colors.lav, borderRadius: radius.full },
  stepMeta: { fontFamily: fonts.bodyMedium, fontSize: 16, color: colors.slateLight, textAlign: 'right' },
  scroll: { flex: 1 },
  body: { padding: spacing.lg, paddingBottom: 110 },
  eyebrow: {
    fontFamily: fonts.bodySemiBold, fontSize: 17, letterSpacing: 1.8,
    textTransform: 'uppercase', color: colors.lav, marginBottom: 12,
  },
  question: { fontFamily: fonts.display, fontSize: 28, lineHeight: 36, color: colors.slate, marginBottom: 8 },
  subtitle: { fontFamily: fonts.body, fontSize: 16, color: colors.slateMid, marginBottom: spacing.lg },
  options: { gap: 10, marginTop: spacing.md },
  option: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    padding: 16, borderWidth: 1.5, borderColor: colors.border,
    borderRadius: 14, backgroundColor: 'white',
  },
  optionSel: { borderColor: colors.lav, backgroundColor: colors.lavPale },
  radio: {
    width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: colors.border,
    alignItems: 'center', justifyContent: 'center',
  },
  radioSel: { borderColor: colors.lav, backgroundColor: colors.lav },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'white' },
  checkbox: {
    width: 20, height: 20, borderRadius: 5, borderWidth: 2, borderColor: colors.border,
    alignItems: 'center', justifyContent: 'center',
  },
  checkboxSel: { borderColor: colors.lav, backgroundColor: colors.lav },
  optText: { fontFamily: fonts.body, fontSize: 17, color: colors.slate, flex: 1 },
  textarea: {
    backgroundColor: colors.cream, borderWidth: 1.5, borderColor: colors.border,
    borderRadius: 14, padding: 14, fontFamily: fonts.body, fontSize: 17,
    color: colors.slate, lineHeight: 24, minHeight: 120, marginTop: spacing.md,
  },
  footer: { paddingHorizontal: spacing.lg, paddingBottom: 32, paddingTop: spacing.sm },
  btn: { backgroundColor: colors.lav, borderRadius: 16, paddingVertical: 17, alignItems: 'center' },
  btnText: { fontFamily: fonts.bodyMedium, fontSize: 16, color: 'white' },
  resultBody: { padding: spacing.lg, gap: spacing.sm },
  resultCard: { borderRadius: radius.lg, padding: spacing.xl, alignItems: 'center' },
  resultIcon: { fontSize: 36, marginBottom: 14 },
  resultTitle: { fontFamily: fonts.display, fontSize: 26, color: 'white', textAlign: 'center', marginBottom: 10 },
  resultDesc: { fontFamily: fonts.body, fontSize: 16, color: 'rgba(255,255,255,0.9)', textAlign: 'center', lineHeight: 22 },
  summaryBox: {
    backgroundColor: colors.cream, borderRadius: 14, padding: spacing.md,
    borderWidth: 1, borderColor: colors.border,
  },
  summaryText: { fontFamily: fonts.body, fontSize: 16, color: colors.slateMid, lineHeight: 22 },
  shareBtn: { backgroundColor: colors.lav, borderRadius: 16, paddingVertical: 17, alignItems: 'center' },
  shareBtnText: { fontFamily: fonts.bodyMedium, fontSize: 16, color: 'white' },
  ghostBtn: { paddingVertical: 12, alignItems: 'center' },
  ghostBtnText: { fontFamily: fonts.body, fontSize: 16, color: colors.slateMid },
  tipCard: {
    backgroundColor: colors.lavPale, borderRadius: 14, padding: spacing.md,
    borderWidth: 1, borderColor: colors.lavLight,
  },
  tipTitle: { fontFamily: fonts.bodyMedium, fontSize: 16, color: colors.lav, marginBottom: 8 },
  tipBody: { fontFamily: fonts.body, fontSize: 17, color: colors.slateMid, lineHeight: 20 },
  journalBadge: {
    backgroundColor: colors.sagePale, borderWidth: 1, borderColor: colors.sageBorder,
    borderRadius: 12, padding: 13, marginBottom: spacing.md,
  },
  journalBadgeTitle: { fontFamily: fonts.bodyMedium, fontSize: 16, color: colors.sage, marginBottom: 4 },
  journalBadgeBody: { fontFamily: fonts.body, fontSize: 16, color: colors.slateMid, lineHeight: 22 },
});
