import { colors } from '../theme';

export const INTERVENTION_CONFIG = {
  escalation_safety: {
    title: 'Please seek immediate help',
    body: 'If you are in crisis, call 988 or go to your nearest emergency room.',
    cta: null,
    accentColor: colors.terraDark,
    bg: colors.terraStrong,
    border: colors.terraBorder,
    icon: 'alert-triangle',
    urgent: true,
  },
  pa_denial_support: {
    title: 'Prior authorization denied',
    body: 'Appeals are common and often successful. Your doctor can help you navigate next steps.',
    cta: 'What you can do',
    accentColor: colors.terraDark,
    bg: colors.terraPale,
    border: colors.terraBorder,
    icon: 'file-text',
    urgent: true,
  },
  positive_reinforcement: {
    title: "You're having a better week",
    body: 'Your recent severity is notably lower than your baseline. Consistency is paying off.',
    cta: 'See your trends',
    accentColor: colors.sageDark,
    bg: colors.sagePale,
    border: colors.sageBorder,
    icon: 'trending-down',
    urgent: false,
  },
  hcp_prep_prompt: {
    title: 'Your data may warrant a doctor conversation',
    body: 'Recent changes in your scores suggest it may be worth reviewing with your healthcare provider.',
    cta: 'Prep for your visit',
    accentColor: colors.lavDark,
    bg: colors.lavPale,
    border: colors.lavLight,
    icon: 'user',
    urgent: false,
  },
  diary_prompt: {
    title: 'Time to log',
    body: "It's been a while since your last entry. Consistent tracking gives you and your doctor better data.",
    cta: 'Log today',
    accentColor: colors.lavDark,
    bg: colors.lavPale,
    border: colors.lavLight,
    icon: 'book-open',
    urgent: false,
  },
  first_dose_coaching: {
    title: 'Starting strong',
    body: 'Preventive treatments take 3–6 months to show their full effect. Consistency now matters more than early results.',
    cta: null,
    accentColor: colors.sageDark,
    bg: colors.sagePale,
    border: colors.sageBorder,
    icon: 'clock',
    urgent: false,
  },
  refill_nudge: {
    title: 'Refill may be coming up',
    body: 'Based on your dose history, a refill may be due soon. Ask your pharmacist or doctor.',
    cta: null,
    accentColor: colors.slateLight,
    bg: colors.creamMid,
    border: colors.border,
    icon: 'refresh-cw',
    urgent: false,
  },
  guidance_unavailable: {
    title: 'Guidance temporarily unavailable',
    body: "We couldn't refresh your personalized guidance right now. Your data is safe.",
    cta: null,
    accentColor: colors.slateLight,
    bg: colors.creamMid,
    border: colors.border,
    icon: 'info',
    urgent: false,
  },
};
